version: '3'

services:
  mongo:
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - /var/db/1/mongo-default-data:/data/db
    networks:
    - net

  mongo-express:
    image: mongo-express:0.49
    depends_on:
      - mongo
    restart: always
    ports:
    - 8084:8084
    environment:
      VCAP_APP_PORT: 8084
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
    - net

networks:
  net:
